image: 'node:14'
before_script:
  - 'apk add --update curl && rm -rf /var/cache/apk/*'

stages:
  - test-prod
  - build-prod
  - deploy-prod

lint-prod:
  stage: test-prod
  tags:
    - SGE
  script:
    - npm ci
    - npm run lint
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 hour
    paths:
      - build
  only:
    - master
  environment: PROD

build-prod:
  stage: build-prod
  tags:
    - SGE
  script:
    - npm ci
    - CI=false
    - npm run build
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 hour
    paths:
      - build
  only:
    - master
  environment: PROD

deploy-prod:
  stage: deploy-prod
  tags:
    - SGE
  image: python:alpine
  script:
    - pip3 install awscli --upgrade
    - aws s3 sync build s3://$BUCKET_NAME
  only:
    - master
  environment: PROD

test-prod:
  stage: test-prod
  tags:
    - SGE
  script:
    - npm ci
    - npm test
  only:
    - master
  environment: PROD
