image: 'node:14'
before_script:
  - 'apk add --update curl && rm -rf /var/cache/apk/*'

stages:
  - test-prod
  - build-prod
  - deploy-prod

lint-prod:
  stage: test-prod
  script:
    - npm ci
    - npm run lint
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 hour
    paths:
      - build
  only:
    - master
  environment: PROD

build-prod:
  stage: build-prod
  script:
    - npm ci
    - CI=false
    - npm run build
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 hour
    paths:
      - build
  only:
    - master
  environment: PROD

deploy-prod:
  stage: deploy-prod
  image: python:alpine
  script:
    - pip3 install awscli --upgrade
    - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - export AWS_DEFAULT_REGION=${REGION}
    - aws s3 sync build s3://${BUCKET}
  only:
    - master
  environment: PROD

test-prod:
  stage: test-prod
  script:
    - npm ci
    - npm test
  only:
    - master
  environment: PROD
